 BG_COLOR='%K{#1a1b26}'    # Background
 FG_COLOR='%F{#c0caf5}'    # Foreground
 COMMENT='%F{#565f89}'     # Comments
 CYAN='%F{#7dcfff}'        # Cyan
 GREEN='%F{#9ece6a}'       # Green
 YELLOW='%F{#e0af68}'      # Yellow
 PURPLE='%F{#bb9af7}'      # Purple
 RED='%F{#f7768e}'         # Red
 ORANGE='%F{#ff9e64}'      # Orange
 RESET='%f%k'              # Reset colors
